### ISSUE TITLE
automate the setup of the virtual environment

### ISSUE THREAD

**Issue by yezz123** [yezz123/setup-uv#6]
```yaml
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: "3.11"
  - uses: yezz123/setup-uv@v1
    with:
      uv-version: "0.1.2"
      uv-venv: ".venv"
  - run: uv --version
```

something like this to automate the setup of virtual environment
