### ISSUE TITLE
🐛 fix uv version implementation 

### ISSUE THREAD

**Issue by yezz123** [yezz123/setup-uv#9]
currently, if we try to install a specific version of uv we implement it like this:

```yaml
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: "3.11"
  - uses: yezz123/setup-uv@v1
    with:
      uv-version: "0.1.5"
  - run: uv --version
```

but as I noticed it installed the default version which is the latest one, i should investigate this here:

https://github.com/yezz123/setup-uv/blob/main/src/inputs.ts#L27-L44

<img width="616" alt="Screenshot " src="https://github.com/yezz123/setup-uv/assets/52716203/b148fbe4-9ecf-424a-8c5b-b6ea04a92282">

Check here: https://github.com/yezz123/authx/actions/runs/7990744469/job/21820221268?pr=546
